name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install requiremnts
      run: sudo apt-get install -y --fix-missing git wget libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build libaio-dev libbluetooth-dev libcapstone-dev libbrlapi-dev libbz2-dev libcap-ng-dev libgtk-3-dev libibverbs-dev libjpeg8-dev libncurses5-dev libnuma-dev librbd-dev librdmacm-dev libsasl2-dev libsdl2-dev libseccomp-dev libsnappy-dev libssh-dev libvde-dev libvdeplug-dev libvte-2.91-dev libxen-dev liblzo2-dev valgrind xfslibs-dev
    - name: Wget qemu-8.2.1
      run: wget https://download.qemu.org/qemu-8.2.1.tar.xz
    - name: tar qemu-8.2.1
      run: tar xf qemu-8.2.1.tar.xz
    - name: rsync
      run: rsync -r qemu-0/hw/3dfx qemu-1/hw/mesa qemu-8.2.1/hw/
    - name: sign commit
      run: bash scripts/sign_commit
    - name: cd qemu-8.2.1
      run: cd qemu-8.2.1
    - name: configure
      run: bash configure --target-list=i386-softmmu
    - name: cd build
      run: cd build
    - name: Ninja
      run: ninja
