name: qemu-linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install requiremnts
      run: sudo apt-get install -y --fix-missing gcc-mingw-w64 mingw-w64-tools curl git gcc-c++ which bison flex texinfo patch zlib-dev tar bzip2 gzip xz unzip python-dev m4 dos2unix nasm diffutils perl-File-Compare perl-Digest-SHA automake autoconf xxd
    - name: env watcom
      run: WATCOM=/opt/openwatcom
    - name: Setup OpenWatcom
      run: curl -OL https://github.com/open-watcom/open-watcom-v2/releases/download/2024-05-02-Build/open-watcom-2_0-c-linux-x64 && chmod +x open-watcom-2_0-c-linux-x64 && TERM=linux script -qefc "./open-watcom-2_0-c-linux-x64 -is" /dev/null  && rm open-watcom-2_0-c-linux-x64
    - name: git clone djgpp GCC
      run: git clone https://github.com/jwt27/build-gcc.git
    - name: sign commit
      working-directory: ./build-gcc
      run: git checkout e7135d2 && sed -i '/build-gdb.sh/d' build-djgpp.sh && ./build-djgpp.sh --target=i686-pc-msdosdjgpp --prefix=/usr/local --batch all
    - name: remove build-gcc
      run: rm -rf build-gcc
    - name: configure
      working-directory: Setup Path
      run:  export PATH=/usr/i686-w64-mingw32/bin/:/usr/local/i686-pc-msdosdjgpp/bin/:/opt/openwatcom/binl64:$PATH
    - name: make 3dfx build folder
      working-directory: ./wrappers/3dfx
      run: mkdir build
    - name: run config wrapper
      working-directory: ./wrappers/3dfx/build
      run: bash ../../../scripts/conf_wrapper
    - name: Make
      working-directory: ./wrappers/3dfx/build
      run: make && make clean

    - name: make mesa build folder
      working-directory: ./wrappers/mesa
      run: mkdir build
    - name: run config wrapper
      working-directory: ./wrappers/mesa/build
      run: bash ../../../scripts/conf_wrapper
    - name: Make
      working-directory: ./wrappers/mesa/build
      run: make && make clean
    - uses: actions/upload-artifact@v4
      with:
       name: wrappers-qemu
       path: ./wrappers/3dfx/build
       path: ./wrappers/mesa/build
